- name: reload and restart journald
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes
    daemon_reload: yes
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
