language: go

go:
  - 1.13.x

script:
  - make fmt test
  - make build build-ctl
  - make docker-build-kubekit docker-build-kubekitctl

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64

after_success:
  - bash <(curl -s https://codecov.io/bash)