- name: check if registry is loaded
  shell: "docker images -q {{ registry_image }}"
  register: is_registry_loaded

- name: check if registry archive exists, if not download to the expected prebake path
  shell: >
    {% set repo = ([ registry_image.split(':')[0], '@', registry_manifest['checksum_type'], ':', registry_manifest['checksum'] ] | join('')) %}
    docker pull {{ repo }} && docker tag {{ repo }} {{ registry_image }} &&
    mkdir -p {{ registry_archive_path | dirname }} &&
    docker save {{ registry_image }} |
    xz -z > {{ registry_archive_path }}
  when: download_images_if_missing
  args:
    creates: "{{ registry_manifest['prebake-path'] }}"

- name: load registry image
  shell: >
    docker_load=$(docker load -i {{ registry_archive_path }})
    && (loaded=$(echo "$docker_load" | awk '{print $NF}')
    && [[ "$loaded" != "tdc/"* ]]
    && ([ $(echo "$loaded" | awk -F':' '{print $1}' | awk -F'/' '{print $1}' | grep '\.') ] && docker tag "$loaded" "tdc/$loaded" || docker tag "$loaded" "tdc/docker.io/$loaded")
    || echo "{{ registry_archive_path }} already loaded")
  when: is_registry_loaded.stdout == ""
