---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ceph-critical
value: 900000000
globalDefault: false
description: |
  Critical pods that are not considered system level and reside in the rook-ceph-system namespace.
  This will still get trumped by the system level critical classes.
