---
apiVersion: v1
kind: List
items:

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-gp2-delete
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: gp2
    reclaimPolicy: Delete

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-gp2-retain
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: gp2
    reclaimPolicy: Retain

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-io1-delete
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: io1
      iopsPerGB: "50"
      fsType: ext4
    reclaimPolicy: Delete

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-io1-retain
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: io1
      iopsPerGB: "50"
      fsType: ext4
    reclaimPolicy: Retain

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-st1-delete
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: st1
      fsType: ext4
    reclaimPolicy: Delete

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-st1-retain
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: st1
      fsType: ext4
    reclaimPolicy: Retain

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-sc1-delete
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: sc1
      fsType: ext4
    reclaimPolicy: Delete

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ebs-sc1-retain
    provisioner: kubernetes.io/aws-ebs
    parameters:
      type: sc1
      fsType: ext4
    reclaimPolicy: Retain
