---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cluster-services
  namespace: kube-system
spec:
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values:
      - "system-node-critical"
      - "system-cluster-critical"
      - "kube-system-critical"
      - "kube-system-high"
