---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: restricted-psp-user
    rules:
    - apiGroups:
      - policy
      resources:
      - podsecuritypolicies
      resourceNames:
      - restricted
      verbs:
      - use

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: restricted-psp-users
    subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: restricted-psp-users
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: privileged-psp-users
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: restricted-psp-user
