---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cluster-services
  namespace: rook-ceph
spec:
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values:
      - "system-node-critical"
      - "system-cluster-critical"
      - "ceph-critical"
