---
apiVersion: v1
kind: Secret
metadata:
  name: rook-s3-object-store-pem
  namespace: rook-ceph
type: Opaque
data:
  cert: {{ cert .certsPath .platform "ingress" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-s3-object-store-ca
  namespace: rook-ceph
type: Opaque
data:
  cert: {{ publicKey .certsPath .platform "ingress_root_ca" | base64Encode }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-s3-object-store
  namespace: rook-ceph
spec:
  # The pool spec used to create the metadata pools
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  # The pool spec used to create the data pool
  dataPool:
    failureDomain: host
    # If you have at least three osds, erasure coding can be specified
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  # Whether to preserve metadata and data pools on object store deletion
  preservePoolsOnDelete: false
  # The gaeteway service configuration
  gateway:
    # type of the gateway (s3)
    type: s3
    # A reference to the secret in the rook namespace where the ssl certificate is stored
    sslCertificateRef: rook-s3-object-store-pem
    # The port that RGW pods will listen on (http)
    port: 80
    # The port that RGW pods will listen on (https). An ssl certificate is required.
    securePort: 443
    # The number of pods in the rgw deployment (ignored if allNodes=true)
    instances: 2
    # Whether the rgw pods should be deployed on all nodes as a daemonset
    allNodes: false
    # The affinity rules to apply to the rgw deployment or daemonset.
    placement:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: role
    #          operator: In
    #          values:
    #          - rgw-node
    #  tolerations:
    #  - key: rgw-node
    #    operator: Exists
    #  podAffinity:
    #  podAntiAffinity:
    resources:
    # The requests and limits set here, allow the object store gateway Pod(s) to use half of one CPU core and 1 gigabyte of memory
    #  limits:
    #    cpu: "500m"
    #    memory: "1024Mi"
    #  requests:
    #    cpu: "500m"
    #    memory: "1024Mi"
    priorityClassName: ceph-storage-critical
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: rook-s3-object-store-default-user
  namespace: rook-ceph
spec:
  store: rook-s3-object-store
  displayName: "default user"
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-rook-s3-object-store-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: rook-s3-object-store
spec:
  ports:
  - name: rgw
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: rook-s3-object-store
  sessionAffinity: None
  type: NodePort
