apiVersion: v1
kind: Secret
metadata:
  name: vcconf
  namespace: kube-system
type: Opaque
data:
   {{ .vsphereServer }}.username: {{ base64Encode .vsphereUsername }}
   {{ .vsphereServer }}.password: {{ base64Encode .vspherePassword }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: vsphere-block-thick
provisioner: kubernetes.io/vsphere-volume
parameters: 
  # datastore: <relying on global default in vsphere.conf, but could have custom classes for apps/users/etc>
  diskformat: zeroedthick
  fstype: ext4

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: vsphere-block-thin
provisioner: kubernetes.io/vsphere-volume
parameters: 
  # datastore: <relying on global default in vsphere.conf, but could have custom classes for apps/users/etc>
  diskformat: thin
  fstype: ext4
